### ISSUE TITLE
Bump SingleStoreDB Version

### ISSUE THREAD

**Issue by xykliu** [singlestore-labs/singlestoredb-dev-image#4]
* SingleStoreDB version number: 7.6.22-3cce9f8118
* Internal Freya Release URL: https://freya.internal.memcompute.com/release/?releaseID=5c37bb07-8f63-40ba-8e57-8497704cbe00

**Comment by carlsverre** [comment]
Thanks! I need to tweak some of the image versioning a bit to handle this case. Will do this week.

**Comment by carlsverre** [comment]
I am releasing a new dynamic version system which will resolve this for customers who need to run 7.6.22.
