### ISSUE TITLE
Bump SingleStoreDB Version

### ISSUE THREAD

**Issue by ionyshch** [singlestore-labs/singlestoredb-dev-image#42]
* SingleStoreDB version number: 8.0.24-959292b1bb
* Internal Freya Release URL: [https://freya.internal.memcompute.com/release/?releaseID=5588cddb-a7ec-4df5-bfbe-238757b2cdb2](https://freya.internal.memcompute.com/release/?releaseID=5588cddb-a7ec-4df5-bfbe-238757b2cdb2)

**Comment by pvetere** [comment]
Cleaning up old issues.
