### ISSUE TITLE
Bump SingleStoreDB Version

### ISSUE THREAD

**Issue by ionyshch** [singlestore-labs/singlestoredb-dev-image#43]
* SingleStoreDB version number: 8.1.18-f6ae627f55
* Internal Freya Release URL: [https://freya.internal.memcompute.com/release/?releaseID=dd01039c-4148-4759-a4c6-6337d85d2ac5](https://freya.internal.memcompute.com/release/?releaseID=dd01039c-4148-4759-a4c6-6337d85d2ac5)

**Comment by pvetere** [comment]
Cleaning up old issues.
